[package]
name = "aitg_proc"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full", "visit-mut"] }

[lib]
proc-macro = true
